version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  open-pull-requests-limit: 99
  schedule:
    interval: "monthly"
  groups:
    dependencies:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: pip
  directory: ".github/workflows/update-tests/"
  open-pull-requests-limit: 99
  schedule:
    interval: "monthly"
  groups:
    dependencies:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
