#! /bin/sh

echo "¶ Running ruff..." && ruff bikeshed && echo "¶ Running black..." && black . && echo "¶ Running mypy..." && mypy && echo "¶ Running pylint..." && pylint bikeshed && echo "✔ All lints passed!"