#! /bin/sh

echo "¶ Running ruff..." && ruff check --fix bikeshed && echo "¶ Running black..." && black . && echo "¶ Running ruff again (just in case)..." && ruff check --fix bikeshed && echo "¶ Running mypy..." && mypy && echo "¶ Running pylint..." && pylint bikeshed && echo "✔ All lints passed!"