[mypy]
exclude = (build)
files = bikeshed/**/*.py
python_version = 3.12
warn_unused_configs = True
allow_redefinition_new = True
disallow_any_generics = True
disallow_untyped_defs = True
enable_error_code = exhaustive-match
local_partial_types = True
no_implicit_optional = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_ignores = True


[mypy-pygments.*]
ignore_missing_imports = True

[mypy-lxml.*]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-isodate.*]
ignore_missing_imports = True

[mypy-alive_progress.*]
ignore_missing_imports = True

[mypy-widlparser.*]
no_implicit_optional = False