<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Local Boilerplate: defaults yes, status yes
External Infotrees: anchors.bsdata yes, link-defaults.infotree yes
Abstract: Find boilerplate and infotrees next to the spec.
Date: 1970-01-01
</pre>

<pre class="biblio">
{
    "EXAMPLE-SPEC": {
        "authors": [ "bar", "baz" ],
        "href": "https://example.test/foo/",
        "title": "Foo Level 1",
        "status": "REC",
        "publisher": "W3C"
    }
}
</pre>

<a>term</a>

[=response=]
