<h1>Advisements</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Index entries should be the original casing, even though dfns are matched case-insensitively.
Abstract: Advisements are normative text with special styling.
Editor: Example Editor
Date: 1970-01-01
</pre>

Advisement: This is an advisements.

This is normative text without styling.

ADVISEMENT: Also an advisement.

NOTE: A note for testing.

Issue: This is an issue.

Advisement: Advisement after an issue.

Unstyled normative text.
