<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Test algorithm auto-naming.
Editor: Example Editor
Date: 1970-01-01
</pre>

<h2 id=foo algorithm>Find a Foo</h2>

Blah blah blah, <var>foo</var>

<h3 id=bar>bar</h3>

<var>foo</var>

<h2 id=foo2>More Stuff</h2>

<div algorithm>
	<dfn>find more foo</dfn>

	<var>foo</var>
</div>

<div algorithm>
	<var>foo</var>
</div>

<div algorithm>
	<dfn>find even more foo</dfn>
	but also <dfn>find some bar</dfn>

	<var>foo</var>
</div>
