<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing inline bibliography generation variations.
Editor: Example Editor
Date: 1970-01-01
</pre>

[[JIS4051 inline]] <!-- inline bibliography for documents without url might not be terribly useful, but should not crash-->

[[RFC2119 inline|custom text here should work]]

[[JIS4051 inline|not sure why inline is useful on a document without a URL, but hey, the syntax's there, so it might as well work]]
