<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing CDDL constructs with generic parameters
Editor: Example Editor
Date: 1970-01-01
Markup Shorthands: markdown yes
</pre>

The CDDL {#cddl}
================

<xmp class=cddl>
; T is always scoped to the Rule that defines it...
one-or-more<T> = T / [ 2* T ]
two-or-more<T> = [ 2* T ]

; even when there's another type with the same name.
generic = "generic"
scoped<generic> = generic

; But, when used, the reference goes to the type!
usage = scoped<generic>

; This is insane but correct
T<T> = {
  T: T
}
</xmp>

Linking to the CDDL {#links}
============================

The {^one-or-more^} type can be referenced, but without the `T`.

There is no way to reference a generic parameter using a shorthand syntax. In the last insane example, `{^T/T^}` is unambiguous and targets the `T` key under the `T` type: {^T/T^}.

To reference a generic parameter, the author must be explicit that the link is to a  `cddl-parameter` definition, as in `<a cddl-parameter for=T>T</a>`: <a cddl-parameter for=T>T</a>.
