<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing CDDL markup and linking with integer keys.
Editor: Example Editor
Date: 1970-01-01
</pre>

<xmp class=cddl>
agent-info-response = {
  response
  1: agent-info ; agent-info
}

response = (
  0: request-id ; request-id
)

agent-info = {
  0: text ; display-name
  1: text ; model-name
  2: [* agent-capability] ; capabilities
  3: text ; state-token
  4: [* text] ; locales
}

request-id = uint

agent-capability = &(
  receive-audio: 1
  receive-video: 2
  receive-presentation: 3
  control-presentation: 4
  receive-remote-playback: 5
  control-remote-playback: 6
  receive-streaming: 7
  send-streaming: 8
)
</xmp>

