<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing CDDL constructs with duplicate values
Editor: Example Editor
Date: 1970-01-01
Markup Shorthands: markdown yes
</pre>

The CDDL {#cddl}
================

<xmp class=cddl>
error = [ "dupl", "dupl" ]
</xmp>

Linking to the CDDL {#links}
============================

The {^error^} type defines the "dupl" value twice. Bikeshed dies with an error message, because there is no way to disambiguate the values. If user forces generation, no dfn is created for the second value.