<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: w3c/ED
ED: http://example.com/foo
Abstract: Testing basic support for conditionals.
Editor: Example Editor
Date: 1970-01-01
</pre>

<div include-if="ED">
    1. Included, since status is ED
</div>

<p include-if="w3c/ED">
    2. Included, since status canonicalizes to w3c/ED.
</p>

<div include-if="ietf/ED">
    Excluded, since megagroup is wrong.
</div>

<div include-if="CR">
    Excluded, since status is not CR.
</div>

<hr>

<div exclude-if="ED">
    Excluded, since status is ED
</div>

<p exclude-if="w3c/ED">
    Excluded, since status canonicalizes to w3c/ED.
</p>

<div exclude-if="ietf/ED">
    3. Included, since megagroup is wrong.
</div>

<div exclude-if="CR">
    4. Included, since status is not CR.
</div>

<p>The attributes <span include-if=ED>5. can</span><span exclude-if=ED>can't</span> be used on inlines as well.</p>

<div include-if="CR, ED">
    6. Included, because at least one condition matched.
</div>

<div include-if="CR, REC">
    Excluded, because none of the conditions matched.
</div>

<div exclude-if="CR, REC">
    7. Included, because none of the exclude conditions matched.
</div>

<div exclude-if="CR, ED">
    Excluded because at least one condition matched.
</div>


8. The end.