<pre class=metadata>
Title: Foo
Org: bikeshed
Group: test
Status: test
Shortname: foo
Level: 1
ED: http://example.com/foo
Abstract: Testing support for &lt;if-wrapper>.
Editor: Example Editor
Date: 1970-01-01
</pre>

<if-wrapper>Excluded and an error, since no conditions.</if-wrapper>

<if-wrapper include-if=TEST>
    <div>1. Included, since the wrapper passes.</div>
</if-wrapper>

<div>
    <if-wrapper include-if=TEST>2. Included, since the wrapper passes.</if-wrapper>
</div>

<if-wrapper include-if=TEST>
    <if-wrapper include-if=TEST>
        <div>3. Stacked wrapper is ok.</div>
    </if-wrapper>
</if-wrapper>

<if-wrapper include-if=TEST>
    <div>4. Stuff between the wrappers
        <if-wrapper include-if=TEST>
            5. also shows up fine.
        </if-wrapper>
    </div>
</if-wrapper>

<if-wrapper exclude-if=TEST>
    Removed, since the wrapper fails.
</if-wrapper>

6. The end.