<pre class=metadata>
Title: Foo
Group: test
Status: TEST
Shortname: foo
Level: 1
ED: http://example.com/foo
Abstract: Testing conditionals over boilerplate and text macros.
Editor: Example Editor
Date: 1970-01-01
Text Macro: FOO 1
Text Macro: bar 2
</pre>

<div include-if="text macro: FOO">
    1. Included, since the FOO text macro exists.
</div>

<div exclude-if="text macro: FOO">
    Excluded since FOO exists.
</div>

<div include-if="TEXT MACRO: FOO">
    2. Included, since FOO exists.
</div>

<div include-if="text macro: foo">
    Excluded, since text macros are case-sensitive.
</div>

<div include-if="text macro: bar">
    Excluded, since 'bar' is lowercase and thus invalid as a text macro.
</div>

<div include-if="text macro: BAR">
    Excluded, since text macros are case-sensitive.
</div>

<div include-if="text macro: qux">
    Excluded, since qux doesn't exist.
</div>

<hr>

<div boilerplate=foo>I'm the foo boilerplate, ignore me.</div>

<div include-if="boilerplate: foo">
    3. Included, since the "foo" boilerplate exists.
</div>

<div include-if="boilerplate: FOO">
    Excluded since boilerplate names are case-sensitive.
</div>

<div include-if="boilerplate: bar">
    Excluded since "bar" doesn't exist.
</div>

4. end