<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing that the CSS datatype range syntax is supported.
Editor: Example Editor
Date: 1970-01-01
</pre>

<<integer [1,10]>>

<<integer [ 1 , 10 ]>>

<<integer [1, ∞]>>

<<integer [∞, 1]>>

<<integer [1, Infinity]>>

<<integer [-Infinity, 1]>>

<<integer [-2, -1]>>

<<integer [-∞, 0]>>

<<integer [-Infinity, 0]>>

<<length [0, 10px]>>

<<length [-20px, Infinity]>>

<<something [0, 20long-unit]>>

<pre class=prod><<integer [0, 10]>></pre>