<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Editor: Example Editor
Date: 1970-01-01
Title: Datablock processing with other elements nearby
Abstract: Just using <pre> indent stripping to test.
</pre>

<style>
pre { border-left: thin dotted; }
</style>

# Standard Behavior {#h1}

	<pre>
			one indent
		no indent
	</pre>

# div on the same line as the start tag {#h2}

<div>div</div><pre>
			one indent
		no indent
	</pre>

# Just an end tag on the same line as the start tag {#h3}

<div>div
</div><pre>
			one indent
		no indent
	</pre>

# Implicit p end tag on the same line as the start tag {#h4}

<p>p
	<pre>
			one indent
		no indent
	</pre>

# div on the same line as the end tag {#h5}

	<pre>
			one indent
		no indent
	</pre><div>div</div>

# div on the same line as a single-line pre {#h6}

foo bar <pre>pre</pre> baz qux
