<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Test several of the datablock types to ensure I preserve attributes/classes on the tag.
Editor: Example Editor
Date: 1970-01-01
</pre>

	<pre attr=foo class=bar>
		some text
			higher indent
	</pre>

<pre attr=foo class="simpledef bar">
Foo: bar
</pre>

<pre attr=foo class="bar railroad">
	T: /*
	ZeroOrMore:
		N: anything but * followed by /
	T: */
</pre>
