<pre class=metadata>
Title: Test
ED: http://example.com/foo
Date: 1970-01-01
Editor: Example Editor
Group: test
Status: LS
Shortname: test
Markup Shorthands: markdown on
Abstract: Testing that figure numbering works.
</pre>

<style>
figure {
	border: thin solid;
	margin: 1em;
	padding: 1em;
	border-radius: .5em;
}
</style>

<figure>
	foo

	<figcaption>first figure</figcaption>
</figure>

<figure>
	<figcaption>second figure, figcaption first</figcaption>

	bar
</figure>

<figure class=table>
	<table><tr><td>foo</table>

	<figcaption>first table</figcaption>
</figure>

<figure>
	baz

	<figcaption>third figure</figcaption>
</figure>

<figure class=table>
	<table><tr><td>bar</table>

	<figcaption>second table</figcaption>
</figure>