<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing that 'Fingerprint Class: None' turns it off.
Fingerprint Class: none
Editor: Example Editor
Date: 1970-01-01
</pre>

Here's some text.

<p class=tracking-vector>Some more text that shouldn't show anything!

<p class=none>Even more text that shouldn't show anything.

And then some more after that.
