<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing that the <code>Force Crossorigin</code> metadata works as expected.
Editor: Example Editor
Date: 1970-01-01
Force Crossorigin: yes
</pre>

<img src=foo>
<video src=foo></video>
<audio src=foo></audio>
<script src=foo></script>
<link href=foo>
<a href=foo>foo</a>

<img crossorigin="use-credentials" src=bar>

<img nocrossorigin src=baz>

<div nocrossorigin>
	<img src=baz>
</div>