<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Editor: Example Editor
Date: 1970-01-01
Title: [LegacyFactoryFunction]
Abstract: Make sure [LegacyFactoryFunction] is supported properly, as a constructor for the interface.
</pre>

<pre class=idl>
[LegacyFactoryFunction=MakeFoo(long arg1, long arg2)]
interface Foo {
  constructor();
};

[LegacyFactoryFunction=MakeBar(long arg1, long arg2)]
interface Bar {
  constructor();
};
</pre>

<dfn constructor for=Foo>MakeFoo(arg1, arg2)</dfn>

<dfn constructor for=Bar>Bar()</dfn>
