<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Higher-kinded types will link in dictmember dfns if they're simple, and at least will never error.
Editor: Example Editor
Date: 1970-01-01
</pre>

<xmp class=idl>
dictionary test {
	sequence<long> member1;
	sequence<(long or boolean)> member2;
	Promise<long> member3;
	Promise<(long or boolean)> member4;
	record<DOMString, long> member5;
	record<DOMString, (long or boolean)> member6;
};
</xmp>

<div dfn-type="dict-member" dfn-for="test">
    : <dfn>member1</dfn>
    : <dfn>member2</dfn>
    : <dfn>member3</dfn>
    : <dfn>member4</dfn>
    : <dfn>member5</dfn>
    : <dfn>member6</dfn>
    ::  test
</div>
