<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing IDL markup and linking.
Editor: Example Editor
Date: 1970-01-01
</pre>

<pre class=idl>
enum BarEnum { "", "bar" };
interface Foo {
	attribute DOMString foo;
 attribute BarEnum bar;
	attribute DOMString _or;
  Promise &lt;any&gt; get(int a);
};
</pre>
<pre class="argumentdef" for="Foo/get(a)">
  a: An argument.
</pre>

{{Foo}}, {{foo}}, {{or}}, {{_or}}
