<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: ED
ED: http://example.com/foo
Abstract: A document with IDL content.
Editor: Example Editor
Date: 1970-01-01
</pre>

<pre class="idl">
    dictionary ExcitingDictionary {
        boolean thingOne;
        boolean thingTwo;
    };

    interface AnInterface {
        boolean aMethod(boolean anArg);
        boolean aMethodToo(optional boolean anArgToo);
        boolean aMethodThree(ExampleDictionary dict);
        boolean aMethodFour(optional ExampleDictionary dictToo);
    };
</pre>
