<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing auto-linking of maplike, setlike, and iterable declarations.
Editor: Example Editor
Date: 1970-01-01
</pre>

<xmp class=idl>
[Exposed=Window]
interface FooIterable {
	iterable<DOMString>;
};

[Exposed=Window]
interface FooMap {
	readonly maplike<DOMString, long>;
};

[Exposed=Window]
interface FooSet {
	readonly setlike<DOMString>;
};
</xmp>
