<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing IDL constructor() support.
Editor: Example Editor
Date: 1970-01-01
</pre>

<pre class=idl>
interface Foo {
	constructor(long bar, optional DOMString baz);
	boolean method(long bar, optional DOMString baz);
	attribute short baz;
};
</pre>

{{Foo()}}, {{Foo/Foo()}}, {{constructor()}}, {{Foo/constructor()}}

{{Foo()/baz}}

{{baz}}