<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing IDL syntax highlighting.
Editor: Example Editor
Date: 1970-01-01
</pre>

<pre highlight=idl>
interface Foo {
	<b>readonly</b> attribute DOMString bar;
	long baz((int or bool) qux1, DOMString? qux2, optional bool qux3);
};
</pre>

<pre class=lang-idl>
interface Foo {
	<b>readonly</b> attribute DOMString bar;
	long baz((int or bool) qux1, DOMString? qux2, optional bool qux3);
};
</pre>

<div class=example>
	<pre class="idl">
	interface Foo {
		<b>readonly</b> attribute DOMString bar;
		long baz((int or bool) qux1, DOMString? qux2, optional bool qux3);
	};
	</pre>
</div>

<script type=idl>
interface Foo {
	readonly attribute Promise<DOMString> bar;
	long baz((int or bool) qux1, DOMString? qux2, optional bool qux3);
};
</script>
