<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Indexing external references defined in local datablocks.
Editor: Example Editor
Date: 1970-01-01
</pre>

<pre class="biblio">
{
    "EXAMPLE-SPEC": {
        "authors": [ "bar", "baz" ],
        "href": "https://example.test/foo/",
        "title": "Foo Level 1",
        "status": "REC",
        "publisher": "W3C"
    }
}
</pre>

<pre class="anchors">
urlPrefix: https://example.test/foo/; spec: EXAMPLE-SPEC
    type: dfn
        text: term
</pre>

<a>term</a>
