<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing explicitly empty for links.
Editor: Example Editor
Date: 1970-01-01
</pre>

<dfn>foo</dfn> (without for) should be linked by <a for="/">foo</a>

<dfn id="foo-bar" for=bar>foo</dfn> (for bar) should be linked by <a for="bar">foo</a>

<style>
:target { background: lime; }
</style>
