<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: ED
ED: http://example.com/foo
Abstract: Testing the various textual links.
Editor: Example Editor
Date: 1970-01-01
</pre>

<style>
:target {
	background: lime;
}
</style>

<h2 id=test>Test</h2>

Setting up the definitions:
<dfn property>property</dfn>,
<dfn descriptor for="@at-rule">descriptor</dfn>,
<dfn at-rule>@at-rule</dfn>,
<dfn type>&lt;type></dfn>,
<dfn value for="property" title="value" id=property-value>value for property</dfn>,
<dfn value for="@at-rule/descriptor" title="value" id=descriptor-value>value for descriptor</dfn>,
<dfn value for="@at-rule" title="value" id=at-rule-value>value for @at-rule</dfn>,
<dfn value for="<type>" title="value" id=type-value>value for &lt;type></dfn>,
<dfn value for="property">different-value</dfn>,
<dfn interface>Interface</dfn>,
<dfn attribute for=Interface>attribute</dfn>,
<dfn method for=Interface>method()</dfn>,
<dfn dictionary>Dictionary</dfn>,
<dfn attribute for="Interface" title="ambiguous-attr" id='interface-attr'>attribute for Interface</dfn>,
<dfn dict-member for="Dictionary" title="ambiguous-attr" id='dict-attr'>attribute for Dictionary</dfn>

Linking:
'property'
'descriptor'
'@at-rule/descriptor'
''@at-rule''
<<type>>
<<'property'>>
<<'descriptor'>>
<<@at-rule>>
<<'@at-rule/descriptor'>>
''property/value''
''descriptor/value''
''@at-rule/descriptor/value''
''&lt;type>/value''
''different-value''
{{Interface}}
{{attribute}}
{{Interface/attribute}}
{{method()}}
{{Interface/method()}}
{{Dictionary}}
{{Interface/ambiguous-attr}}
{{Dictionary/ambiguous-attr}}
<a idl for="Interface">attribute</a>
