<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing magic link-text correction.
Editor: Example Editor
Date: 1970-01-01
</pre>

<dfn>berry</dfn>
<a>berries</a>

<dfn>blockify</dfn>
<a>blockified</a>

<dfn>zero</dfn>
<a>zeroes</a>
<a>zeroed</a>
<a>zeroing</a>

<dfn>bikeshed</dfn>
<a>bikeshed's</a>
<a>bikeshed’s</a>
<a>bikesheds</a>

<dfn>foos</dfn>
<a>foos’</a>

<dfn>snap</dfn>
<a>snapped</a>
<a>snapping</a>

<dfn>generate</dfn>
<a>generated</a>
<a>generating</a>

<dfn interface>Interf</dfn>
<dfn attribute for=Interf>_attr</dfn>
{{attr}}
