<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing macros in various opaque blocks
Editor: Example Editor
Text Macro: REPLACEME (successful replacement!)
Text Macro: NOTAMACRO (if you see this, replacement happened when it shouldn't)
</pre>

<pre>
foo [REPLACEME] bar
</pre>

<pre class=railroad>
T: [NOTAMACRO]
</pre>

<pre class=railroad bs-macros>
T: [REPLACEME]
</pre>

<script>
var NOTAMACRO = 1;
var arr = [NOTAMACRO];
</script>

<script bs-macros>
var REPLACEME = 1;
var arr = [REPLACEME];
</script>

<style>
.foo {
	content: "[NOTAMACRO]";
}
</style>

<style bs-macros>
.bar {
	content: "[REPLACEME]";
}
</style>

<xmp>
<em>[NOTAMACRO]</em>
</xmp>

<xmp bs-macros>
<em>[REPLACEME]</em>
</xmp>