<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Test of markdown code constructs.
Editor: Example Editor
Date: 1970-01-01
Markup Shorthands: markdown on
Boilerplate: omit document-revision
</pre>

"code1": `code1`

"code2": This is `code2`.

"code spaces": This one has `code spaces`.

"lots of code spaces": This one has `three   spaces` in it.

"code link": This one is <a href="#">in a `code link`</a>.

"not code": Here's some \`literal backticks\`

"multi-backtick code": This code is ``delimited ``` by two `s``, so it can include single or triple backticks.

"spaces on the sides": This`` ` ``code has leading and trailing space, which should be stripped so the backtick is snug between the words.

"more spaces": this``  `   ``code has 2 leading and 3 trailing spaces, of which one each should be stripped.

"just spaces": this``  ``code is just two spaces, which shouldn't be stripped

"newlines": `this
code
has` newlines in it, which should be turned into spaces.

"side newlines": This``
`
``code starts and ends with newlines, which should also be stripped, so the backtick is snug between the words.

"code block"
```
This is a code block.
```

"tilda code block"
~~~
this code block has tildas,
```
and isn't closed by backticks
```
~~~


foo

"long code block"
````
this code block starts with 4 backticks
```
so it's not closed by the 3 backticks above
but it's closed with way more than 4 backticks
````````

some final non-code text to make sure things get closed correctly


"code block with tabs"
```
	A leading tab
		Two leading tabs
An inline 	tab following a single space.
```
