<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: ED
ED: http://example.com/foo
Abstract: Test of markdown constructs
Editor: Example Editor
Date: 1970-01-01
</pre>

Double-Underline Heading
======================== {#a}

text

Single-Underline Heading
------------------------ {#b}

text

# One-Hash Heading # {#c}

text

## Two-Hash Heading ## {#d}

text

### Three-Hash Heading ### {#e}

text

#### Four-Hash Heading #### {#f}

text

##### Five-Hash Heading ##### {#g}

text

###### Six-Hash Not-A-Heading ###### {#h}

Tight Bulleted List
===================

* one
* two
* three

Loose Bulleted List
===================

* one

* two

* three

List With Paragraphs
====================

* one
one
one

	another paragraph
	one
one

* two

Nested Lists
============

* one

	* nested one
	* nested two
* two
