<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Make sure that lists don't over-claim lines when they dont' end with a blank line.
Editor: Example Editor
Date: 1970-01-01
</pre>

<section>
	: dt one
	:: dd one

	: dt two
	:: dd two
</section>

<section>
	: dt one
	:: dd one

	: dt two
	:: dd two
		dd two second line
</section>

<section>
	* one

	* two
</section>

<section>
	* one

	* two
		two second line
</section>
