<h1>Foo</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Test of markdown blockquotes
Editor: Example Editor
Date: 1970-01-01
Markup Shorthands: markdown on
</pre>

> quote1
> quote1
> quote1

> quote2
quote2
> quote2
quote2
quote2

> quote3
quote3
* unrelated bullet

> quote 4

> quote5
---
> quote 6

> * bulleted quote7
* unrelated bullet

paragraph
> quote8

> > nested quote
equally nested

> > nested quote
>
> not nested

	> quote 9
unrelated text
