<pre class=metadata>
Title: foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Wrapping an MD-generated list in a list container of the appropriate type uses the manual list-container, so you can put classes/etc on it.
Editor: Example Editor
Date: 1970-01-01
</pre>



<ol class=foo>
	1. one
	2. two
		1. two.one
		2. two.tow
	3. three
</ol>

<ol class="foo">
	* one
	* two
	* three
</ol>
