<pre class=metadata>
Title: Test
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Blockquote processing happens *before* HTML parsing, but lone lines are fine.
Editor: Example Editor
Date: 1970-01-01
Markup Shorthands: markdown-blockquotes on
</pre>

<div
> a lone tag is just fine, parsed as a tag
</div>


<div foo=bar
> but two of them in consecutive lines <span foo=bar
> will trigger the blockquote parsing and break</span></div>


> <div
> > a lone tag inside of a blockquote breaks</div>


> <div
> >and so does<span
> >two in a row</span></div>
