<pre class=metadata>
Title: Test
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Nesting opaques into a blockquote does *not* work.
Editor: Example Editor
Date: 1970-01-01
Markup Shorthands: markdown-blockquotes on
</pre>

> <pre>
> > this isn't
> > a blockquote
> </pre>
>
> <xmp>
> > this isn't
> > a blockquote
> </xmp>
>
>
> ```
> > this isn't
> > a blockquote
> ```
>
> <script>
> > this isn't
> > a blockquote>
> </script>
>
> <style>
> > this isn't
> > a blockquote
> </style>