<pre class='metadata'>
Title: Test
Shortname: your-spec
Level: 1
Status: LS
Group: test
URL: http://example.com/url-this-spec-will-live-at
Editor: Your Name, Your Company http://example.com/your-company, your-email@example.com, http://example.com/your-personal-website
Abstract: A short description of your spec, one or two sentences.
Version History: http://example.com/foo
!Foo: some foo
!Bar: link to [[#intro]] <b>bold</b> bar <b>more bold</b> more bar
!Bar2: link to [[#intro]] <b>bold</b> bar <b>more bold</b> more bar
!Baz: some baz
!Version History: foo <b>bold</b> bar <b>more bold</b> baz
Metadata Include: Foo no, Editor no, Baz yes
Metadata Order: Version History, Bar, *, !*
</pre>

Introduction {#intro}
=====================

Spec metadata should contain the following keys, in order: Version History, Bar, This version, Bar2, Baz.

"Bar" and "Bar2" should contain mixed text and several inline elements.
