<h1>Notes</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: ED
ED: http://example.com/foo
Abstract: Index entries should be the original casing, even though dfns are matched case-insensitively.
Abstract: Notes and issues should be generated correctly.
Editor: Example Editor
Date: 1970-01-01
</pre>

Note: This is a note.

Note, this too is a note.

NOTE: Also this.

NOTE, notes! Though I don't like this syntax, it's easy.

Issue: This is an issue.

ISSUE: THIS IS AN ISSUE OMG!!!!11!!!1!
