<pre class=metadata>
Title: Foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Testing &lt;pre class=def> parsing.
Editor: Example Editor
Date: 1970-01-01
</pre>

<pre class=simpledef>
key1: val1
key1: val2
key2: val1
key1: val3 merges with the others
key3:: first : splits the key from val
f&amp;o: HTML entities allowed
<code>foo</code>: HTML code allowed
<code>foo:</code>: But no HTML parsing - first literal : splits key from val.
<code>foo&#x3a;</code>: Escaping works, tho.
</pre>

