<pre class=metadata>
Title: Foo
Group: test
Shortname: foo-bar
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: "from biblio" and manual Previous Version entries can be mixed.
Previous Version: https://example.com/first
Previous Version: from biblio
Previous Version: https://example.com/third
Editor: Example Editor
Date: 1970-01-01
</pre>


<pre class=biblio>
{
	"foo-bar-1": {
		"authors": [
			"Tab Atkins",
			"Dirk Schultze"
		],
		"href": "http://www.w3.org/TR/foo-bar-1/",
		"title": "Foo Bar Level 1",
		"status": "CR",
		"publisher": "W3C",
		"deliveredBy": [
			"http://www.w3.org/html/wg/"
		]
	},
	"foo-bar-1-20100102": {
		"authors": [
			"Tab Atkins",
			"Dirk Schultze"
		],
		"href": "http://www.w3.org/TR/CR-foo-bar-1-20100102/",
		"title": "Foo Bar Level 1",
		"status": "CR",
		"publisher": "W3C",
		"deliveredBy": [
			"http://www.w3.org/html/wg/"
		]
	},
	"foo-bar-1-20200202": {
		"authors": [
			"Tab Atkins",
			"Dirk Schultze"
		],
		"href": "http://www.w3.org/TR/REC-foo-bar-1-20200202/",
		"title": "Foo Bar Level 1",
		"status": "REC",
		"publisher": "W3C",
		"deliveredBy": [
			"http://www.w3.org/html/wg/"
		]
	},
	"foo-bar-2": {
		"authors": [
			"Tab Atkins",
			"Dirk Schultze"
		],
		"href": "http://www.w3.org/TR/foo-bar-2/",
		"title": "Foo Bar Level 2",
		"status": "CR",
		"publisher": "W3C",
		"deliveredBy": [
			"http://www.w3.org/html/wg/"
		]
	},
	"foo-bar-2-20100102": {
		"authors": [
			"Tab Atkins",
			"Dirk Schultze"
		],
		"href": "http://www.w3.org/TR/CR-foo-bar-2-20100102/",
		"title": "Foo Bar Level 2",
		"status": "CR",
		"publisher": "W3C",
		"deliveredBy": [
			"http://www.w3.org/html/wg/"
		]
	}
}
</pre>