<h1>Section Links</h1>

<pre class=metadata>
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: Section links are awesome.
Editor: Example Editor
Date: 1970-01-01
</pre>

<h2 id="a">Section A</h2>

<a section href="#e"></a>

<h2 id="b">Section B</h2>

<a section href="#a"></a>

<h2 id="c">Section C</h2>

<a section href="#d"></a>

<h2 id="d">Section D</h2>

<a section href="#b">Override</a>

<h2 id="e">Section <var>var</var></h2>
