<pre class=metadata>
Title: foo
Group: test
Shortname: foo
Level: 1
Status: LS
ED: http://example.com/foo
Abstract: A document without any content.
Editor: Example Editor
Date: 1970-01-01
</pre>

Both of the following should produce warnings. Also, the data-algorithm attributes should be correctly set.

<h2 algorithm="Make a string.">
  String creation
</h2>

Let |var| be a string.

<h2 algorithm>
  Make a non-string.
</h2>

Let |var| be anything other than a string. Really. Anything.
