<pre class='metadata'>
Title: Progressive Font Enrichment, or whatever we call it
Shortname: PFE
Status: w3c/ED
Group: webfontswg
Level: none
TR: https://www.w3.org/TR/example/
ED: https://w3c.github.io/PFE/Overview.html
Editor: Chris Lilley, W3C, https://svgees.us/, w3cid 1438
Editor: Myles C. Maxfield, Apple Inc., mmaxfield@apple.com, w3cid 77180
Editor: Garret Rieger, Google Inc., http://example.com/contact
Abstract: Example example
Status Text: This is a largely empty document because we have just started working on it.
</pre>

<!--
    for things that are not in specref
    https://www.specref.org/
-->
<pre class=biblio>
	{
		"PFE-report": {
            "href": "https://www.w3.org/TR/PFE-evaluation/",
            "authors": [
                "Chris Lilley"
                ],
            "status": "Note",
            "publisher": "W3C",
			"title": "Progressive Font Enrichment: Evaluation Report",
			"date": "15 October 2020"
		}
	}
</pre>

Introduction {#intro}
=====================

	<em>This section is not normative.</em>

    The success of WebFonts is unevenly distributed. This specification allows WebFonts to be used where slow networks, very large fonts, or complex subsetting requirements currently preclude their use. For example, even using WOFF 2 [[WOFF2]], fonts for CJK languages are too large to be practical.

    See the Progressive Font Enrichment: Evaluation Report [[PFE-report]] for the investigation which led to this specification.

Sample section {#sample-topic}
==============================

@@ actual spec text goes here.

Binary format {#binary-format}
==============================

The format used is CBOR (Concise Binary Object Representation) [[!rfc8949]].

<h2 class=no-num id=priv-sec>Privacy and Security Considerations</h2>

Issue: Note any issues that have been raised about privacy and security.
