<h1>UI Events</h1>

<pre class="metadata">
Shortname: uievents
Level:
Group: uievents
Status: WD
TR: http://www.w3.org/TR/uievents/
ED: https://w3c.github.io/uievents/
Repository: w3c/uievents
Previous Version:
	https://www.w3.org/TR/2015/WD-uievents-20151215/
	http://www.w3.org/TR/2015/WD-uievents-20150428/
	http://www.w3.org/TR/2015/WD-uievents-20150319/
Editor: Gary Kacmarcik, Google, garykac@google.com
Editor: Travis Leithead, Microsoft, travil@microsoft.com
Editor: Doug Schepers, Mar 2008 - May 2011
!Tests: <a href=https://github.com/w3c/web-platform-tests/tree/master/uievents>web-platform-tests uievents/</a> (<a href=https://github.com/w3c/web-platform-tests/labels/uievents>ongoing work</a>)
Abstract:
	This specification defines UI Events which extend the DOM Event objects
	defined in [[DOM]]. UI Events are those typically implemented by visual
	user agents for handling user interaction such as mouse and keyboard input.
</pre>

<pre class="link-defaults">
spec:dom; type:interface; text:Document
</pre>

<pre class="anchors">
urlPrefix: http://www.w3.org/TR/WebIDL/#idl-; type: type;
	text: long
urlPrefix: http://w3c.github.io/selection-api/#widl-Window-getSelection-Selection; type: dfn; for: Document
	text: getSelection()
url: http://www.w3.org/TR/2004/REC-xml-20040204/#NT-S; type: dfn;
    text: white space
url: http://www.w3.org/TR/uievents/#; type: dfn; spec: uievents-key;
	text: key attribute value
url: https://www.w3.org/TR/uievents-key/#keys-modifier; type: dfn; spec: uievents-key;
	text: modifier keys table
url: https://html.spec.whatwg.org/multipage/forms.html#context-menus; type: dfn;
	text: contextmenu
</pre>

<pre class="link-defaults">
spec:infra; type:dfn; text:code point
</pre>

<pre class="biblio">
{
	"DWW95": {
		"title": "Developing International Software for Windows 95 and Windows NT: A Handbook for International Software Design",
		"authors": [ "N. Kano" ],
		"publisher": "Microsoft Press",
		"date": "1995",
		"isbn": "1-55615-840-8"
	},
	"PCRE": {
		"title": "Perl Compatible Regular Expressions library",
		"href": "http://www.pcre.org/"
	},
	"US-ASCII": {
		"title": "Coded Character Set - 7-Bit American Standard Code for Information Interchange",
		"publisher": "Standard ANSI X3.4-1986",
		"date": "1986"
	},
	"WIN1252": {
		"title": "Windows 1252 a Coded Character Set - 8-Bit",
		"href": "http://www.microsoft.com/globaldev/reference/sbcs/1252.htm",
		"publisher": "Microsoft Corporation"
	}
}
</pre>

<pre class="include">
path: sections/introduction.include
</pre>

<pre class="include">
path: sections/conventions.include
</pre>

<!-- Section 3: Architecture =============================================== -->
<pre class="include">
path: sections/architecture.include
</pre>

<!-- Section 4: Basic Event Interfaces =====================================
<pre class="include">
path: sections/event-interfaces.include
</pre>
-->

<!-- Section 5: The Events ================================================= -->
<pre class="include">
path: sections/event-types.include
</pre>

<!-- Section 6: Keyboard and key values ==================================== -->
<pre class="include">
path: sections/keyboard.include
</pre>

<!-- Appendix A: Legacy Event Initializers ================================= -->
<pre class="include">
path: sections/legacy-event-initializers.include
</pre>

<!-- Appendix B: Legacy Key Attributes ===================================== -->
<pre class="include">
path: sections/legacy-key-attributes.include
</pre>

<!-- Appendix C: Legacy Event Types ======================================== -->
<pre class="include">
path: sections/legacy-event-types.include
</pre>

<!-- Appendix D: Extending Events ========================================== -->
<pre class="include">
path: sections/extending-events.include
</pre>

<!-- Appendix E: Security Considerations =================================== -->
<pre class="include">
path: sections/security.include
</pre>

<!-- Appendix F: Changes =================================================== -->
<pre class="include">
path: sections/changes.include
</pre>

<!-- Appendix G: Acknowledgements ========================================== -->
<pre class="include">
path: sections/acknowledgements.include
</pre>

<!-- Appendix H: Glossary  ================================================= -->
<pre class="include">
path: sections/glossary.include
</pre>
