<pre class="metadata">
<!-- The basics. Please change all of these values appropriately. -->
Title: Privacy-Preserving Example API
Shortname: shortname
Repository: privacycg/shortname
URL: https://privacycg.github.io/shortname/
<!-- Replace NNNNN with your w3cid, which is the number at the end of the url when you navigate to https://www.w3.org/users/myprofile -->
Editor: Your Name, w3cid NNNNN, Your Employer https://employer.example/, you@employer.example
Abstract: This specification defines the Example API, an exciting new method to invoke example methods from within a web browser.
<!-- Choose a status. This is either a specification or a non-normative report. Several samples are commented out below. -->
<!-- Status Text: This is a non-normative report. It is not a W3C standard nor is it on the W3C standards track. -->
<!-- Status Text: This specification is intended to be migrated to the W3C standards track. It is not a W3C standard. -->
<!-- Status Text: This specification is intended to be merged into the HTML Living Standard. It is neither a WHATWG Living Standard nor a W3C standard. -->
<!-- Choose a license. You should pick the license used by your intended destination on the standards track. The two most probable licenses are provided as examples below. -->
<!-- Text Macro: LICENSE <a href=http://www.w3.org/Consortium/Legal/2015/copyright-software-and-document>W3C Software and Document License</a> -->
<!-- Text Macro: LICENSE <a href=https://creativecommons.org/licenses/by/4.0/>Creative Commons Attribution 4.0 International License</a> -->
<!-- Leave the rest of this metadata alone. -->
Group: privacycg
Status: CG-DRAFT
Level: None
</pre>

<section class="non-normative">
<h2 id="intro">Introduction</h2>

<em>This section is non-normative.</em>

Blah blah blah.
</section>

<h2 id="infra">Infrastructure</h2>

This specification depends on the Infra standard. [[!INFRA]]

<h2 id="acknowledgements" class="no-num">Acknowledgements</h2>

Many thanks to
Some Body,
Somebody Else,
and
A. Third Person
for their feedback on this proposal.
