#!/usr/local/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'Bikeshed','console_scripts','bikeshed'
__requires__ = 'Bikeshed'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
    )
