<pre class='metadata'>
Title: CSS Subtree Visibility
Shortname: css-subtree-visibility
Level: 1
Status: UD
Group: csswg
Work Status: exploring
URL: https://wicg.github.io/display-locking
Editor: Tab Atkins-Bittner, Google
Editor: Vladimir Levin, Google
Abstract: This spec introduces a subtree-visibility CSS property, allowing authors
          to control element subtree visibility, while at the same time providing strong
          rendering performance hints to the user-agent. The user-agent can use the hints
          to optimize rendering performance, making interactions with large amounts of
          content perform well.
</pre>

Introduction {#intro}
============

Subtree Visibility (a.k.a. Display Locking) is a CSS property designed to allow
developers and browsers to easily scale to large amount of content and provide
strong hints which allow the user-agent to delay rendering <a href=#f1>[1]</a>
work.  More concretely, the goals are:

* Avoid rendering work for content not visible to the user.
* Support user-agent features and all layout algorithms (e.g. responsive
    design, flexbox, grid) for this content.

Optimizing behavior and performance of the following use-cases motivate this work:

* Fast display of large HTML documents (examples: HTML one-page spec; other
    long documents)
* Scrollers with a large amount of content, without resorting to virtualization
    (examples: Facebook and Twitter feeds, CodeMirror documents)

Motivation & Background {#motivation}
-----------------------

On the one hand, faster web page loads and interactions directly improve the
user experience of the web. On the other hand, web sites each year grow larger
and more complex than the last, in part because they support more and more use
cases, and contain more information. The most common UI pattern for the web is
scrolling, which leads to pages with a lot of non-visible (off-screen or hidden)
DOM. Since the DOM presently renders atomically, it inherently takes more and
more time to render on the same machine.

Web developers are in a good position to know whether rendering a particular
[=subtree=] that is off-screen is needed for the visual representation of their
page. Specifically, if the layout of an off-screen box and its [=subtree=] has a
visible and necessary effect on screen then such rendering is required.
Otherwise, it is not. Since web developers are in a good position to have this
information, they can provide the user-agent strong hints indicating that
rendering for a given [=subtree=] is not required in certain cases.

Traditionally, two techniques of providing this information to the user-agent
are to mark non-visible DOM as "invisible" <a href=#f2>[2]</a>, or to use
virtualization <a href=#f3>[3]</a>. Browser implementors also want to reduce
loading and rendering time of web apps. Common techniques to do so include
adding caching of rendering state <a href=#f4>[4]</a>, and avoiding rendering
work <a href=#f5>[5]</a> for content that is not visible.

These techniques can work in many cases but have drawbacks and limitations:

* <a href=#f2>[2]</a> and <a href=#f3>[3]</a> usually means that such content
    is not available to user-agent features, such as find-in-page functionality.
    Also, content that is merely placed off-screen may or may not have rendering
    cost (it depends on browser heuristics), which makes the technique
    unreliable.

* Caching intermediate rendering state is hard work, and often has performance
    limitations and cliffs that are not obvious to developers.  Similarly,
    relying on the browser to avoid rendering for content that is clipped out or
    not visible is sometimes not reliable, as it's hard for the browser to
    efficiently detect what content is not visible and does not affect visible
    content in any way.

Previously adopted web APIs, in particular the 'contain' and 'will-change' CSS
properties, add ways to specify forms of rendering isolation or isolation
hints, with the intention of them being a mechanism for the web developer to
help the browser optimize rendering for the page.

While these forms of isolation help, they do not guarantee that isolated
content does not need to be rendered at all.  Ideally there would be a way for
the developer to specify that specific parts of the DOM need not be rendered,
and pair that with a guarantee that when later rendered, it would not
invalidate more than a small amount of style, layout, or paint in the rest of
the document.

Definitions {#definitions}
===========

* <dfn export>subtree</dfn>: an element's subtree are all nodes that comprise
    the [=flattened element tree=] rooted at the given element, with the exception
    of the element itself. In other words, this refers to the [=flat tree=]
    descendants of the element. Note that the term <em>subtree</em> in the
    property name 'subtree-visibility' refers to the same descendants.
* <dfn export>off-screen</dfn>: an element is considered to be off-screen if
    its border box does not intersect the visual viewport plus a user-agent
    specified, margin. 
    <div class=note>
      The the user-agent is free to consider any margin around the viewport
      when computing whether the element is off-screen. The margin is meant to
      allow the user-agent to start preparing the element ahead of time, before
      it enters the viewport. A 50% viewport margin is a reasonable
      implementation default.
    </div>
* <dfn export>on-screen</dfn>: an element is considered to be on-screen if it
    is not [=off-screen=]
* <dfn export>skipped</dfn>: an element is considered skipped if its [=subtree=] is
    not painted or hit-tested. A skipped element has [=layout containment=],
    [=style containment=], and [=size containment=] applied to it in addition to
    other containment values. The user-agent should avoid as much rendering work
    in the skipped element's [=subtree=] as possible.
    <div class=note>
      Rendering work can be avoided due to the combination of
      containment and the fact that the [=subtree=] is not painted.  As an example,
      because of the containment applied, in most cases it should be possible to skip
      computing styles, or determining layout box sizes and positions, unless
      explicitly requested by script.
    </div>
* <dfn export>gains containment</dfn>: for an an element to gain containment,
    the user-agent must apply [=layout containment=] and [=style containment=]
    to it in addition to any other containment properties.

The 'subtree-visibility' property {#subtree-visibility}
=================================

<pre class=propdef>
Name: subtree-visibility
Value: visible | auto | hidden
Initial: visible
Inherited: no
</pre>

<dl dfn-type value dfn-for=subtree-visibility>
    : <dfn export>visible</dfn>
    :: No effect. This provides no extra information or hints to the user-agent.

    : <dfn export>auto</dfn>
    :: The element [=gains containment=]. 
         If *all of* the following conditions hold then the element is also [=skipped=]:
           * The element is [=off-screen=].
           * Neither the element nor any of its [=subtree=] elements are
               focused as described in the <a
               href="https://html.spec.whatwg.org/multipage/interaction.html#focus">focus</a>
               section of the HTML spec.
           * Neither the element nor any of its [=subtree=] elements are
               selected as described in the <a
               href="https://drafts.csswg.org/css-pseudo-4/#highlight-pseudos">highlight
               pseudo-elements</a> section.

         It is important to note that the contents of the [=subtree=] must be
         accessible to user-agent features such as find-in-page, tab order
         navigation, etc. This is true regardless of whether the element is
         [=skipped=] or not.

    : <dfn export>hidden</dfn>
    :: The element is [=skipped=].

         Note that in this case, the contents of the [=subtree=] are not accessible
         to user-agent features, such as find-in-page, tab order navigation,
         etc.
</dl>

Note that when the element is [=skipped=] and the rendering work is avoided,
the user-agent should retain the previously computed layout state if possible.

<div class=note>
  Intuitively, a [=hidden=] value means that the element behaves in a way that
  does not expose the contents of its [=subtree=] to the user (but still has an
  effect on layout, especially in conjunction with `contain-intrinsic-size`).
  Script interactions are required for the content to appear to the user.

  In contrast, a value of [=auto=] means that the element behaves as if the
  contents of the [=subtree=] are accessible to the user. The content can be
  interacted with in the usual ways: scrolling will reveal the content, tab
  order navigation will visit the [=subtree=], find-in-page will find matches, etc.
  The fact that [=off-screen=] elements with ''subtree-visibility: auto'' are
  [=skipped=] is a rendering performance optimization.

  Note that selected and focused elements affected by ''subtree-visibility: auto''
  are treated as if they are painted, since users can interact with this
  content when it is off-screen. For example, a user can copy (via a shortcut)
  text that was selected and scrolled off-screen. For this reason, elements and
  subtrees with focus or selection remain painted.
</div>

<div class=note>
  It is worthwhile to note the interaction between 'subtree-visibility' and
  containment: If the element has a 'subtree-visibility' value other than
  [=visible=], the user-agent enforces [=style containment=] and [=layout
  containment=] on the element. Additionally, if the element is [=skipped=],
  then the user-agent also enforces [=size containment=]. These containment
  values are added on top of any existing containment values.
</div>

Restrictions and Clarifications {#restrictions}
===============================

* In situations where [=layout containment=] has no effect (e.g. the
    element does not generate a principal box), 'subtree-visibility' values also
    have no effect.

* <a href="https://html.spec.whatwg.org/multipage/rendering.html#replaced-elements">
    Replaced elements</a> do not paint their contents if they
    are [=skipped=] due to 'subtree-visibility'. That is, the element's border
    and background are painted, but the replaced content -- as described in
    steps 7.1 and 7.2.4 of <a
    href="https://www.w3.org/TR/CSS21/zindex.html#painting-order">the painting
    order</a> steps -- is not.

* From the perspective of an <a
    href="https://w3c.github.io/IntersectionObserver/">intersection observer</a>,
    elements in the [=subtree=] of a [=skipped=] element are not intersecting the <a
    href="https://w3c.github.io/IntersectionObserver/#dom-intersectionobserver-root">root</a>.
    This is true even if both the root and the target elements are in the [=subtree=]
    of a [=skipped=] element.

* From the perpsective of a <a
    href="https://drafts.csswg.org/resize-observer/#resize-observer-interface">resize
    observer</a>, elements in the [=subtree=] of a [=skipped=] element do not
    change their size. If these elements become non-skipped again, the resize
    observation will be delivered if the new size differs from the last size
    used to notify the resize observer.

Accessibility {#accessibility}
=============

Similar to the way 'subtree-visibility' affects painted output of the element's
[=subtree=], it also affects information exposed to the
<a href="https://w3c.github.io/css-aam/#dfn-accessibility-tree">accessibility
tree</a> and <a href="https://w3c.github.io/css-aam/#dfn-assistive-technology">
assistive technologies</a>:
* Subtrees affected by ''subtree-visibility: visible'' or ''subtree-visibility: auto''
    that are not [=skipped=] should be included in the accessibility tree as usual.
* Subtrees of [=skipped=] elements should not be included in the accessibility tree,
    with the following exception:
    * Subtrees which are affected by ''subtree-visibility: auto'' and are
        [=skipped=] should be also be included in the accessibility tree
        subject to the rendering constraints below.

<div class=note>
  Since assistive technologies may provide quick access to offscreen elements,
  it is desirable that elements in ''subtree-visibility: auto'' subtrees be made
  available to assistive technologies to provide this functionality, since they
  are intended to be observable to users.

  Conversely, since elements in ''subtree-visibility: hidden'' subtrees are not
  intended to be observable by users, they should not be exposed to assistive
  technology.
</div>

* The rendering performance of subtrees affected by 'subtree-visibility' and
    exposed to assistive technologies must reasonably match the rendering
    performance of the same subtrees exposed to painted output.

<div class=note>
  The requirement of rendering performance equivalency stems from privacy
  considerations. It is imperative that the user-agent ensures that a page
  using 'subtree-visibility' cannot use timing information to deduce whether
  the user is using assistive technologies. For this reason, the rendering
  performance of information exposed to assistive technologies must be the same
  as the rendering performance of information exposed to painted output.

  In other words, if the user-agent omits rendering work when producing painted
  output, then it must also omit the same rendering work when providing
  information for assistive technologies, and vice-versa.
</div>

<div class=note>
  If the user-agent omits rendering work, then it should still make the effort
  to expose ''subtree-visibility: auto'' [=skipped=] elements and their
  subtrees to assistive technology without exposing any of the layout state,
  since it is not available due to omitted work.

  If such action is not possible, then the user-agent may omit these subtrees
  from the accessibility tree.
</div>

Examples {#examples}
========

<div class=example>
	<xmp highlight=markup>
		<style>
		.sv {
		  subtree-visibility: auto;
      min-height: 50px;
		}
		</style>

		<div class=sv>
		  ... some content goes here ...
		</div>
	</xmp>

  The .sv element's 'subtree-visibility' value [=auto=] lets the user-agent
  manage whether the element is [=skipped=].  Specifically when this element is
  near the viewport, the user-agent will begin painting the element.  When the
  element moves away from the viewport, it will stop being painted. In
  addition, the user-agent should skip as much of the rendering work as
  possible when the element is [=skipped=].
</div>

<div class=example>
	<xmp highlight=markup>
		<style>
		.sv {
		  subtree-visibility: hidden;
		}
		</style>

		<div class=sv>
		  ... some content goes here ...
		</div>
	</xmp>

  In this case, the element is [=skipped=] regardless of viewport intersection.
  This means that the only way to have this [=subtree=] painted is via script
  updating the value to remove 'subtree-visibility' or change its value. As
  before, the user-agent should skip as much of the rendering in the [=subtree=] as
  possible.

  An additional effect of skipping rendering is that the layout state of the
  [=subtree=] can be preserved by the user-agent, so that removing the
  'subtree-visibility' property in the future will cause the [=subtree=] to be
  rendered quicker than otherwise possible.
</div>

<div class=example>
	<xmp highlight=markup>
		<style>
    body {
      margin: 0;
    }
		.sv {
		  subtree-visibility: hidden;

      position: relative;
      left: 10px;
      top: 20px;
		}
    #child {
      position: relative;
      left: 1px;
      top: 2px;

      width: 100px;
      height: 200px;
    }
		</style>

		<div id=target class=sv>
      <div id=child></div>
		  ... some other content goes here ...
		</div>
    <script>
      ...
      // This will force rendering work, including layout,
      // if the UA previously avoided it.
      target.firstElementChild.getBoundingClientRect();
      ...
    </script>
	</xmp>

  Similarly to the last example, the element is [=skipped=]. The user-agent
  should avoid as much rendering work as possible.  However, in this example,
  at some point script accesses a layout value in the element's [=subtree=]. In
  this situation, the user-agent cannot avoid rendering work and has to process
  any previously skipped rendering work in order to return a correct value to
  the caller. In this example, the result of getBoundingClientRect is a rect
  positioned at (11, 22) with a size 100x200.

  Note that repeated calls to the same layout value should not
  cause any additional rendering work, since the user-agent should retain the
  last updated rendering state.

  Also note that this situation in which rendering work is required is not
  unique. There may be other situations in which the user-agent cannot avoid
  rendering work. 
</div>

Similarity to visibility {#similarity}
========================

Note that 'subtree-visibility' bears some similarity in naming to 'visibility'
which is important to address. Like 'visibility', 'subtree-visibility' controls
whether the element, or its [=subtree=], are painted and hit-tested. However, it
has important distinctions that allow both adoption in a wider set of use-cases
and ability for user-agents to optimize rendering performance:

* 'subtree-visibility' values cannot be reverted by descendant style. As an
    example, when processing an element that has 'subtree-visibility' value
    [=hidden=], the user-agent will not paint any of its subtree, even if one of
    the elements in the [=subtree=] has 'subtree-visibility' value [=visible=]. This
    is important as it makes it possible to skip style part of rendering in
    these [=subtree=], since no descendant value can override 'subtree-visibility'.
* 'subtree-visibility' has an [=auto=] value, which allows the user-agent to
    paint the element's [=subtree=] when it approaches the viewport. This allows easy
    adoption of the feature. In contrast, if 'visibility' or ''display: none'' are
    used instead, then it is up to the developer to toggle the values when they
    approach the viewport.
* 'subtree-visibility' adds in containment. This is an important part of the
    property, which allows the user-agent to skip rendering work in the [=subtree=],
    since it can reason that when the element's [=subtree=] is not painted, then the
    style and layout effects of the [=subtree=] will not affect any visible content.

Alternatives Considered {#alternatives}
=======================

The ''display: none'' CSS property causes content subtrees not to render.
However, there is no mechanism for user-agent features to cause these subtrees
to render. Additionally, the cost of hiding and showing content cannot be
eliminated since ''display: none'' does not preserve the layout state of the
[=subtree=].

''visibility: hidden'' causes subtrees to not paint, but they still need style
and layout, as the [=subtree=] takes up layout space and descendants may be
''visibility: visible''. Note that with sufficient containment and intersection
observer, the functionality provided by 'subtree-visibility' may be mimicked.
However, ''subtree-visibility: auto'' also permits user-agent algorithms such
as find-in-page and fragment navigation to access the element's [=subtree=], which
cannot be mimicked by ''visibility''. Overall, 'subtree-visibility' property is
a stronger signal allowing the user-agent to optimize rendering.

Similar to ''visibility: hidden'', ''contain: strict'' allows the browser to
automatically detect subtrees that are definitely off-screen, and therefore
that don't need to be rendered. However, ''contain: strict'' on its own is not
flexible enough to allow for responsive design layouts that grow elements to
fit their content. To work around this, content could be marked as ''contain:
strict'' when off-screen and then some other value when on-screen (this is
similar to 'subtree-visibility'). Second, ''contain: strict'' may or may not
result in rendering work, depending on whether the browser detects the content
is actually off-screen. Third, it does not support user-agent features in
cases when it is not actually rendered to the user in the current application
view.


Privacy & Security Considerations {#priv-sec}
=================================

tbd


Footnotes {#footnotes}
=========

<p id=f1>[1]: Meaning, the rendering part of the browser event loop.

<p id=f2>[2]: Examples:
placing ''display:none'' CSS on DOM subtrees,
or by placing content far off-screen via tricks like ''margin-left: -10000px''

<p id=f3>[3]: In this context,
virtualization means representing content outside of the DOM,
and inserting it into the DOM only when visible.
This is most commonly used for virtual or infinite scrollers.

<p id=f4>[4]: Examples:
caching the computed style of DOM elements,
the output of text / block layout,
and display list output of paint.

<p id=f5>[5]: Examples:
detecting elements that are clipped out by ancestors,
or not visible in the viewport,
and avoiding some or most rendering lifecycle phases for such content.
