<h1>Foo</h1>

<pre class=metadata>
Shortname: foo
Level: 1
Status: ED
ED: http://example.com/foo
Abstract: Foo.
Editor: Tab Atkins
</pre>

Foo Section
==========={#foo}

Bar Subsection
--------------{#bar}

	foo foo foo
	1. foo foo foo
	foo foo foo
	<span class='note'>foo</span> foo

	* bar bar bar
	bar bar bar
	<baz>baz baz baz</baz>

	foo foo

	<em>foo foo</em>

More Foo
========{#more-foo}

	foo foo foo
