# Consider moving this to run as part of ci.yml

name: Playwright Tests
on:
#  push:
#    branches-ignore:
#      - "dependabot/**"
#      - "daily-test-sync"

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      # Note: the version of the docker container for playwright must exactly match the version used in package.json.
      image: mcr.microsoft.com/playwright:v1.35.1-jammy
    steps:
        - uses: actions/checkout@v4

        # Steps for Playwright testing with container
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run your tests
          run: npx playwright test
        - uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: test-results
            path: test-results/
            retention-days: 30
