name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy
    steps:
        - uses: actions/checkout@v3

        # Steps for Bikeshed testing
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            pip install --upgrade pip wheel
            pip install --editable .
        - name: Test with bikeshed
          run: bikeshed test tests/caniuse001.bs

        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run your tests
          run: npx playwright test


    # Steps for Playwright testing without container
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: 16
    # - name: Install Playwright dependencies
    #   run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
